### ISSUE TITLE
Question about dataset

### ISSUE THREAD

**Issue by logic03** [dluthwy/SignLanguageRecognition#2]
Hello, there is no file XF500_Body_Depth_TXT. Zip in the CSL500 data set I applied for. May I ask whether this is to extract the Z coordinates or XY coordinates in each frame (a frame has 25 joint labels)?The official Pose label provided is the normalized XY coordinate and the actual depth (m) Z coordinate.

________________________________________________________________________________________________________________

您好，我申请得到的CSL500数据集中没有xf500_body_depth_txt.zip这一个文件，请问这个是把每一帧（一帧有25个关节标签）中的z坐标还是xy坐标提取出来呢？官方提供的pose标签是归一化后的xy坐标和实际深度（以m）为单位的z坐标。

**Comment by harveyfly** [comment]
你可以自己分析一下官方数据集的数据格式
